# Generated by Django 4.2.23 on 2025-08-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_comment_updated_at_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.CharField(default='shrek', max_length=50),
            preserve_default=False,
        ),
    ]
